name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18', '16', '14', '12']
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Installing Dependencies
        run: npm ci

      - name: Linting Codebase
        run: npm run lint

      # build first
      - name: Building Artifacts
        run: npm run build

      # then test
      - name: Unit Testing
        run: npm run test
